server:
  port: 8080
  servlet:
    context-path: /project
spring:
  elasticsearch:
    rest:
      uris: http://127.0.0.1:9200
      connection-timeout: 10
      read-timeout: 30
  flyway:
    enabled: true
    locations: classpath:db/dev
    baseline-on-migrate: true
    out-of-order: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ghost?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&useUnicode=true
    username: ghost
    password: 3GJaRKs6JLdfYnLs
swagger:
  service:
    base-package: 'com.soul.rat.controller'
    description: open-api
    enable: true
    group-name: '@project.real.name@'
    title: '@project.real.name@'
    version: '@project.real.version@'
mybatis-plus:
  mapper-locations: classpath*:com/soul/rat/mapper/*:xml

logging:
  level:
    com:
      soul:
        rat:
          mapper: debug
